version: "3.0"
services:
  apache-php:
    build:
      dockerfile: apache-php7.2.Dockerfile
      args:
       - PHP_VERSION=${PHP_VERSION}
      context: .
    restart: always
    volumes:
     - "${VHOSTS_DIR}:/etc/apache2/sites-available"
     - "${PROJECTS_PATH}:/var/www"
    ports:
      - "${APACHE_PORT}:80"
      - "${SSH_PORT}:22"
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    volumes:
     - "${MYSQL_DATA_DIR}:/var/lib/mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}