version: "3.0"
services:
  apache-php7.2:
    build:
      dockerfile: apache-php7.2.Dockerfile
      args:
       - PHP_VERSION=${PHP_VERSION}
      context: .
    restart: always
    environment:
     - PHP_VERSION=${PHP_VERSION}
    volumes:
     - "${VHOSTS_DIR}:/etc/apache2/sites-available"
     - "${PROJECTS_PATH}:/var/www"
    ports:
      - "${APACHE_PORT}:80"
      - "${SSH_PORT}:22"
  mysql-5.7:
    image: mysql:5.7
    restart: always
    volumes:
     - "${MYSQL_DATA_DIR}:/var/lib/mysql"